### ISSUE TITLE
Remove e-mail from README

### ISSUE THREAD

**Issue by paulodiovani** [Codeminer42/marvin-cm42#9]
Remove the e-mail address from any part of the code where it is listed.

The Gmail Connector should be able to be used with any e-mail address.

Changes required:

- [ ] remove email ocurrences, and replace to `you@example.com`
- [ ] update instructions, if necessary (see also #4)

**Comment by PedroRorato** [comment]
Hi, @paulodiovani, I checked the whole project and I found email addresses in only 3 files:

- package.json;
- scripts/google.js ( "marvin@codeminer42.com" commented on lines 7 and 8)
- lib/google/retrieveEmail.js: "support@egghead.io - line 42" ; "yourfriends@streamyard.com - line 55" ; "marvin@codeminer42.com - line 61"

1. Which ones do you want me to replace or include in .env file?

**Comment by paulodiovani** [comment]
done in #40
